import { Inter } from "next/font/google";
import "./globals.css";
import "material-symbols/rounded.css";
import { ToastProvider } from "@/_contexts/toastContext";
import { Toaster } from "@/_components/toaster/toaster";
import { ModalProvider } from "@/_contexts/modalContext";
import  ModalRoot  from "@/_components/modals/modalRoot/modalRoot";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "aguilaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable}` }>
      <body>
        <ModalProvider>
          <ToastProvider>
            <Toaster position="top-right"/>
            <ModalRoot/>
            {children}
          </ToastProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
